### ISSUE TITLE
Support for ResNet32

### ISSUE THREAD

**Issue by agnusmaximus** [mc2-project/delphi#14]
Hi @Pratyush and @ryanleh

Does this repository support evaluation of ResNet32 (obtaining accuracy of ResNet32 on Cifar100, as well as benchmarking latency performance)?

**Comment by ryanleh** [comment]
* By evaluating accuracy of ResNet32 do you mean the accuracy of the plaintext model? Or the accuracy when using Delphi? The former can be done independently of Delphi using whatever toolset you've used to train your model. The latter is possible to test (by modifying [this](https://github.com/mc2-project/delphi/blob/79c85607a6d265d05c28f8c3d27d0f7b64b28b7c/rust/experiments/src/validation/minionn/validate.rs#L50) line) but won't be particularly informative. This is because Delphi's neural network library only supports networks with consecutive layers. As a result, Delphi does not support the identity shortcut connections in the ResNet32 network so the current implementation will probably not be accurate. 

  Note that for MiniONN, using Delphi incurs a negligible error rate (than .05%) compared to the plaintext model in inference. Thus, if we had implemented the identity shortcuts mentioned above we would expect that Delphi's accuracy for Restnet32 would be nearly equivalent to the underlying plaintext model.

* The identity shortcut connections mentioned above don't affect the latency of the inference, however. To test latency, run the following on the server:
```cargo +nightly run --bin resnet32-server --release --all-features -- -l {NUM OF POLY LAYERS}```
and the following on the client:
```cargo +nightly run --bin resnet32-client --release --all-features -- -l {NUM OF POLY LAYERS} -i {SERVER IP}```

Let me know if this answers your questions!

**Comment by agnusmaximus** [comment]
This makes sense, thank you!
