### ISSUE TITLE
Delphi paper / configuration questions

### ISSUE THREAD

**Issue by dnat112** [mc2-project/delphi#18]
1. The Delphi paper mentions that a random one time pad key is hardwired into the ReLU circuit. What does this mean? Why does MUSE refer to the same data as an "input" of the server instead?

2. What was the reason for the choice of a 41-bit prime to define the prime field? (Why not use a smaller prime instead?)

3. Why does Delphi use public key encryption for the homomorphic layers instead of symmetric encryption?

Thanks!

**Comment by ryanleh** [comment]
Thanks for the questions 😄 

1. Nice catch! They actually mean the same thing. In both cases, the OTP used by the server is an input to the garbled circuit. However, since this OTP does not depend on anything else, the server can generate it during garbling and send its corresponding labels to the client alongside the circuit itself in the offline phase. Thus, the OTP is effectively 'hardwired' into the circuit from the client's perspective. Muse does the same thing but just didn't explicitly mention this.

2. Using a smaller prime field leads to decreased accuracy in the inference, and may cause overflow if it gets too small. That being said I believe there were some more specific reasons why we chose that prime that I don't recall: @Pratyush might remember?

3. I'm not sure I follow, how exactly would one use symmetric encryption to do the homomorphic pre-processing?

**Comment by dnat112** [comment]
1. That makes sense. Thanks!

2. For more context, the original (Usenix) version of Delphi says this:

> Concretely, our implementation works over the 32-bit prime finite field defined by the prime 2138816513, and uses a 15-bit fixed-point representation. This choice of parameters enables a single multiplication of two fixed-point numbers before the result overflows capacity of the prime field. 

But the later eprint version of Delphi says this:

> Concretely, our implementation works over the 41-bit prime finite field defined by the prime 2061584302081, and uses a 11-bit fixed-point representation. This choice of parameters enables a single multiplication of two fixed-point numbers before the result overflows capacity of the prime field.

In the first version, it seemed like the choice to make the prime 32 bits was related to the fact that multiplying two 15-bit numbers would result in at most a 30-bit number, which would be less than the 32-bit prime. But in the second version, this reasoning doesn't seem to apply. Would you be able to clarify what was meant then by these sentences?

3. Sorry, what I said above wasn't clear. I meant why does Delphi use asymmetric homomorphic encryption to do the homomorphic encryption parts instead of symmetric _homomorphic_ encryption. I'm possibly misunderstanding something, but it seems to me that the client is the only one doing any homomorphic encryptions (and decryptions), and the server is only ever performing homomorphic _evaluations_. Is this correct? If this is the case, why would the client need to use asymmetric homomorphic encryption at all instead of symmetric homomorphic encryption?

4. Another question came up which is relevant to the Issue title, so I'll add it here (hope that's ok). I noticed in the Delphi code for the ReLU garbled circuit, Delphi doesn't perform the garbled circuit ReLU part over all of the 41 bits of input. Instead, it seems that Delphi assumes that the input value would not be larger than a certain value, and just computes the garbled circuit for a few bits more than 11-bits. If my understanding is correct, do Delphi's runtime and communication results in the paper include this optimization? Also, how exactly did you arrive at the conclusion that the results would not be larger than the maximum value assumed in the code?

Thank you!

**Comment by ryanleh** [comment]
2. Ok, I re-synced with Pratyush to recall why we made those exact choices (not sure how I forget this as I spent a ton of time working on it haha). As you mention, originally we had used a 32-bit prime in order to allow for two multiplication + a few additions (the additions add to the bit width marginally so a 30 or 31-bit prime would overflow).
  
      After the initial submission, we ran some accuracy experiments to make sure our inference accuracy was close to the plaintext inference accuracy. We found that the error introduced by truncation was much larger then we had originally hypothesized because of a failure case that SecureML hadn't caught (see section 5.1.1 of [this paper](https://eprint.iacr.org/2018/403.pdf)). This large error occurs with a probability dependent on the amount you truncate + the size of the prime field. So to fix this we bumped up our prime field size and lowered our fixed-point representation size... this caused the failure to occur with much lower probability: Delphi's inference was 99% as accurate as the underlying plaintext inference.

    Sorry if that's a bit much, let me know if it makes sense 😄 

3. The server only performs evaluations (and no encryptions) in Delphi so what you describe should be true. However, I am not familiar with any symmetric homomorphic encryption schemes or libraries for them? Do these currently exist? We used [this](https://github.com/microsoft/SEAL#microsoft-seal-1) library which is based on [this](https://eprint.iacr.org/2012/144.pdf) construction.

4. Yes, this is because the value has been truncated before it is inputted to the garbled circuit. The circuit checks the sign-bit, returning 0 if it's negative, and if it's positive we know it's only 11-bits wide at most due to truncation so we can just perform the ReLU on that portion. Yes, our experimental numbers include this optimization.

**Comment by fionser** [comment]
@ryanleh 
Yes, I have the same local truncation issue here. 

Suppose the prime bit is `41`, and using about `11` bit for the scaling factor. 

Then the local truncation (right after the multiplication) should fail with the probability of `p = 2^{11*2 - 41) = 2^{-19}`. 

This should be a problem since for a larger CNN.  For example, in the `first CONV` layer of ResNet50 of ImageNet, the number of output pixels is `802,816 (112x112x64)`. Then there is a probability  about  `1 - (1 - p)^802,816 ~ 78%` that at least one of the local truncation failed. Given the fact that the pixel values of ImageNet  range between [-128, 128] after normalization. The ratio of local truncation failed would be far more larger than 78%. When the local truncation failed, the resulting value will become a large "random" value and propagate to all the following layers.

BTW, I go through the previous code in delphi's conv [implementation](https://github.com/mc2-project/delphi/blob/de77cd7b896a2314fec205a8f67b257df46dd75c/rust/protocols-sys/c%2B%2B/src/lib/conv2d.cpp#L112) , the random mask is sampled from [0, 2^20) which is should come from [0, p) (e.g., about [0, 2^41)). Which might explain why the previous local truncation in delphi  work.
