### ISSUE TITLE
Skipping training and extraction

### ISSUE THREAD

**Issue by tolusophy** [mc2-project/delphi#31]
Hi! I am confused about something.
Let's say I've got an entirely different model and I have saved its weights to a h5 format, can I just go ahead to the inference and skip the other steps listed in the readme?

**Comment by ryanleh** [comment]
No, the rust backend uses PyTorch, which has a different serialization format than h5 so there needs to be some conversion. If you already have an h5 file, simply run the `extract_keras_weights.py` script as specified in the README to get a numpy file which the inference can then use.

**Comment by tolusophy** [comment]
Oh! I actually have it in pytorch pth...I was thinking of converting to h5 through onnx. So what should I do with the pth

**Comment by ryanleh** [comment]
Hmm so to be a bit more specific, the conversion script adjusts some tensor dimensional differences between Keras and Pytorch and then serializes the entire model as a `.npy` file. So you would still have to serialize the `.pth` file into `.npy`. I would take a look [here](https://github.com/mc2-project/delphi/blob/424c653222b8215444faa004caff43a9e7480fb5/python/extract_keras_weights.py#L93), and see if you can tweak the function to not do any re-shaping of the `.pth` model. Otherwise, you could convert to h5 and then use the script.

**Comment by tolusophy** [comment]
Thank you
