### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by aliarastehfard** [mc2-project/delphi#45]
Hi, I am trying to run `validate.rs` using 
`cargo +nightly run --release --bin minionn-accuracy -- --weights PATH/TO/MODEL/WEIGHTS --images /home/USER/research/delphi/rust/experiments/src/validation/images --layers 0`; 
however, I keep getting this error:
``
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 98, kind: AddrInUse, message: "Address already in use" }', experiments/src/lib.rs:67:44 
``
Do you know as to what might be causing this problem and how I can fix it?
Thanks in advance.

**Comment by aliarastehfard** [comment]
I'm also getting this:
``thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }', experiments/src/lib.rs:54:47``

**Comment by ryanleh** [comment]
Hi, the first error is occurring because the server is trying to bind to port 8001 but another process is already using that port. I would check to see which process is using the port and kill it (e.g. if you're on Linux you can do something like [this](https://unix.stackexchange.com/questions/106561/finding-the-pid-of-the-process-using-a-specific-port) to find the PID, and then run `kill {PID}`). This will probably fix both issues (the second error is the client failing to connect to the server).

**Comment by aliarastehfard** [comment]
Thank you for your response. I actually did kill it. It turned out that the same process was using it. But still I get the "connection refused" error. Any idea what could be preventing the client from connecting to the server?
![image](https://user-images.githubusercontent.com/49977238/220161474-73d6476a-afbc-420f-aaf3-51dd2855dfaa.png)

**Comment by ryanleh** [comment]
Hm not off the top of my head. Usually these error messages are due to a firewall being mis-configured, but I believe this test just uses the local loopback address so that shouldn't be interfering. Are you running this inside a container? That could also cause issues.

In the meantime I would try a `pgrep minionn-accuracy` to make sure there aren't any stray processes. If there aren't then I would do something like `nmap -Pn 127.0.0.1` or `nmap -Pn 0.0.0.0` and check that a service is running successfully on port 8001.

**Comment by aliarastehfard** [comment]
> 
Thank you very much! It has something to do with my system. I'm gonna leave it for later haha. It runs just fine in another system (on Chameleon). As for my system, I did as you instructed but yet couldn't figure out what was the problem. Is a conda environment considered as a container? Anyways, I deactivated it and still encountered the same problem.

**Comment by ryanleh** [comment]
Hm no, conda shouldn't affect things at all
