### ISSUE TITLE
Bit width between FHE and Secret sharing.

### ISSUE THREAD

**Issue by fionser** [mc2-project/delphi#6]
Hi.
A quick question. 
For SEAL (currently delphi  use the BFV scheme) can provide a message space of a small number of bits (e.g., 10~16bits)
But, additive secret sharing might need more than 64bits.
My question is that, how does delphi (or where in the source code) address this various bit width problem ? 

Many thanks !

**Comment by ryanleh** [comment]
Hi,
Thanks for the questions!
* Seal can provide a message space up to ~64 bits if I remember correctly. Currently, Delphi uses a 41-bit prime with modulus defined [here](https://github.com/mc2-project/delphi/blob/a0bd25d7b5b5bd1b9dabad9fc47f960330878c1c/rust/algebra/src/fields/near_mersenne_64/mod.rs#L14).
* The additive secret sharing does not require over 64 bits because we truncate intermediate values. Please see Remark 4.2 of the [paper](https://eprint.iacr.org/2020/050.pdf#subsection.4.3) for more details.

Let me know if this answers your questions!

**Comment by fionser** [comment]
@ryanleh  

Hi,
A quick question on the masking vector added to the homomorphic results (FC, CONV)

Suppose the HE message space is `t` (a prime)
The additive secret sharing works over `p` (a prime) 

Server:
 Enc(m), m \in [0, t)
- random r as a share
- response Enc(m - r), and decrypt obtain a share `m - r mod t`

My question is
`In which range should the masking vector's value taken from, so that the security is kept. `

**Comment by ryanleh** [comment]
Hi,
The masking vector needs to be sampled randomly from the message space in order to ensure security 👍

**Comment by fionser** [comment]
@ryanleh  If `r` is sampled from `[0, t)`
Then how the additive share can be reconstructed in `mod q` if `q < t`.
For example, `t = 13` and `q = 11`, 
the message to share is `m = 3`, and let the `r = 11`.
then after decryption one party gets `m - r mod t = 5` as the A-share of `m`.
Another party's A-share of `m` is `r mod q = 0`. It seems this two shares can not reconstruct `m` i.e., `5 + 0 mod q != m`

**Comment by Pratyush** [comment]
We use the same primes for HE and for secret sharing, so there's no errors arising from a mismatch of the moduli.
