### ISSUE TITLE
Compile error: Feature has been removed (const_fn)

### ISSUE THREAD

**Issue by lvdmaaten** [mc2-project/delphi#8]
When trying to compile using `cargo`, I run into the following error:
```
(crypten) lvdmaaten@devfair0297:~/secure_mpc/delphi/rust$ cargo +nightly build --release
   Compiling algebra v0.1.0 (/private/home/lvdmaaten/secure_mpc/delphi/rust/algebra)
warning: couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
warning: set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable
error[E0557]: feature has been removed
  --> algebra/src/lib.rs:28:12
   |
28 | #![feature(const_fn)]
   |            ^^^^^^^^ feature has been removed
   |
   = note: split into finer-grained feature gates

error: aborting due to previous error

For more information about this error, try `rustc --explain E0557`.
error: could not compile `algebra`
```
Any advice on how to resolve this compile error?

**Comment by lvdmaaten** [comment]
Replacing the relevant line by `#![feature(const_fn_trait_bound)]` resolved this issue for me.

The library then builds successfully and so the the tests (with some warning about null pointer dereferences). But some of the tests appear to fail: `test gc::test::test_relu ... FAILED`

The benchmarks do not compile.

**Comment by ryanleh** [comment]
Thanks for bringing this up! The feature issue is due to some recent changes. If you want to make a PR for the change that would be great, otherwise I will update things within a few weeks. I will get to the benchmarks within a week or so (I haven't touched the benchmarks for awhile since we relied primarily on the `experiments` folder for benchmarks, so I'm not surprised they don't currently compile). 

Could you provide some more details about the null pointer warnings? I don't believe I've seen those before. 

The ReLU test should fail as there's a bug that was never fixed. If the resulting error trace shows an off-by-one from the expected result than everything is fine.

**Comment by ryanleh** [comment]
Hi! The compilation issue + benchmark issues are fixed now :+1: 

I will making a PR hopefully later this week which fixes some stuff in the C++ backend (including the null pointer warnings).
